# Generated by Django 4.0.5 on 2022-06-06 12:39

import datahub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('address', models.JSONField()),
                ('phone_number', models.CharField(max_length=50)),
                ('logo', models.CharField(blank=True, max_length=500, null=True)),
                ('hero_image', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[(1, 'is_active'), (0, 'is_inactive')], default=1, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrganizationMap',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(verbose_name='accounts.User')),
                ('organization_id', models.UUIDField(verbose_name=datahub.models.Organization)),
            ],
        ),
    ]
