# Generated by Django 4.0.5 on 2022-06-06 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datahub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorganizationmap',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datahub.organization'),
        ),
        migrations.AlterField(
            model_name='userorganizationmap',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
