# Generated by Django 4.0.5 on 2022-06-07 04:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0002_alter_userorganizationmap_organization_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userorganizationmap',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
