# Generated by Django 4.0.5 on 2022-06-08 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0002_alter_organization_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='email',
            new_name='org_email',
        ),
        migrations.AlterField(
            model_name='userorganizationmap',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
