# Generated by Django 4.1.5 on 2023-12-06 07:46

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0040_alter_datasetv2_name_alter_policy_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LangchainPgCollection",
            fields=[
                ("name", models.UUIDField()),
                ("cmetadata", models.JSONField()),
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "langchain_pg_collection",
            },
        ),
        migrations.CreateModel(
            name="LangchainPgEmbedding",
            fields=[
                ("collection_id", models.UUIDField()),
                ("embedding", pgvector.django.VectorField(verbose_name=1563)),
                ("document", models.TextField()),
                ("cmetadata", models.JSONField()),
                ("custom_id", models.CharField(max_length=255)),
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "langchain_pg_embedding",
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=250)),
                ("category", models.JSONField(default=dict)),
                (
                    "user_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datahub.userorganizationmap",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResourceFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="users/resources/"
                    ),
                ),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("youtube", "youtube"), ("pdf", "pdf")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("url", models.CharField(max_length=200, null=True)),
                (
                    "transcription",
                    models.CharField(blank=True, max_length=2500, null=True),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="datahub.resource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
