# Generated by Django 4.1.5 on 2023-12-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "datahub",
            "0041_langchainpgcollection_langchainpgembedding_resource_and_more",
        ),
        ("datahub", "0041_resource_resourcefile"),
    ]

    operations = []
