# Generated by Django 4.1.5 on 2023-12-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0042_merge_20231207_0944"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LangchainPgCollection",
        ),
        migrations.DeleteModel(
            name="LangchainPgEmbedding",
        ),
        migrations.AlterField(
            model_name="resourcefile",
            name="type",
            field=models.CharField(
                choices=[("youtube", "youtube"), ("pdf", "pdf"), ("file", "file")],
                max_length=20,
                null=True,
            ),
        ),
    ]
