# Generated by Django 4.1.5 on 2023-12-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0043_delete_langchainpgcollection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="resource",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
