# Generated by Django 4.1.5 on 2024-03-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0074_alter_resourcefile_transcription"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="metadata",
            field=models.JSONField(default={}, null=True),
        ),
    ]
