# Generated by Django 4.1.5 on 2024-03-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0075_messages_metadata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messages",
            old_name="metadata",
            new_name="output",
        ),
    ]
