# Generated by Django 4.1.5 on 2024-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0076_rename_metadata_messages_output"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messages",
            name="output",
        ),
        migrations.AlterField(
            model_name="resource",
            name="description",
            field=models.TextField(max_length=2048),
        ),
    ]
