# Generated by Django 4.1.5 on 2024-09-27 10:44

import json

from django.db import migrations


def convert_country_to_json(apps, schema_editor):
    Resource = apps.get_model('datahub', 'Resource')
    for resource in Resource.objects.all():
        try:
            # If the current country data is just a plain string, wrap it in a JSON format
            # For example, if the current field contains "India", it will convert to {"country": "India"}
            if resource.country:
                resource.country = json.dumps({"name": resource.country})
                resource.save()
        except Exception as e:
            print(f"Error converting country for resource {resource.id}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0082_resource_district_resource_state_resource_village_and_more'),
    ]

    operations = [
                migrations.RunPython(convert_country_to_json),

    ]
