# Generated by Django 4.1.5 on 2024-09-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0083_auto_20240927_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='country',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='resource',
            name='district',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='resource',
            name='state',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='resource',
            name='village',
            field=models.JSONField(default=dict),
        ),
    ]
