# Generated by Django 4.1.5 on 2024-09-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0084_alter_resource_country_alter_resource_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='district',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='village',
            field=models.JSONField(default=dict),
        ),
    ]
