# Generated by Django 4.0.5 on 2022-08-11 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0001_initial'),
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectors',
            name='user_map',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='datahub.userorganizationmap'),
            preserve_default=False,
        ),
    ]
