# Generated by Django 4.0.5 on 2022-08-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_alter_connectors_user_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorsmap',
            name='ports',
            field=models.JSONField(default={}),
        ),
    ]
