# Generated by Django 4.1.5 on 2023-09-02 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datahub', '0040_alter_datasetv2_name_alter_policy_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('selected_columns', models.JSONField()),
                ('access_key', models.CharField(blank=True, max_length=100, null=True)),
                ('dataset_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='datahub.datasetv2file')),
            ],
        ),
    ]
