# Generated by Django 4.1.5 on 2023-09-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='access_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='api',
            name='endpoint',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
