# Generated by Django 4.1.5 on 2024-05-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("microsite", "0002_inspection"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Inspection",
        ),
    ]
