# Generated by Django 4.0.5 on 2022-06-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscription",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
