# Generated by Django 4.0.5 on 2022-06-07 08:29

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userrole',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
