# Generated by Django 4.0.5 on 2022-06-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userrole_remove_user_username_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, to='accounts.userrole'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(max_length=255),
        ),
    ]
