# Generated by Django 4.0.5 on 2022-06-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
