# Generated by Django 4.0.5 on 2022-06-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("datahub_admin", "datahub_admin"),
                    ("datahub_guest_user", "datahub_guest_user"),
                    ("datahub_participant_root", "datahub_participant_root"),
                    ("datahub_participant_team", "datahub_participant_team"),
                    ("datahub_team_member", "datahub_team_member"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
