# Generated by Django 4.1.5 on 2023-10-05 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0055_remove_datasets_user_map_and_more'),
        ('accounts', '0004_alter_user_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datahub.organization'),
        ),
    ]
