# Generated by Django 4.0.5 on 2022-06-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userrole_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
