# Generated by Django 4.0.5 on 2022-06-07 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_role_user_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, max_length=255, on_delete=django.db.models.deletion.PROTECT, related_name='role', to='accounts.userrole'),
            preserve_default=False,
        ),
    ]
