# Generated by Django 4.0.5 on 2022-06-07 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_role_id_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, max_length=255, on_delete=django.db.models.deletion.PROTECT, related_name='role', to='accounts.userrole'),
        ),
    ]
